DELETE http://localhost:3001/api/contacts/4424a5d0c91346006b85d8eee3d67a88
###
GET http://localhost:3001/api/contacts/
###
POST http://localhost:3001/api/contacts
content-type: application/json

{
    "name": "Adi Lovelace", 
    "number": "39-44-5323523"
}
###
GET http://localhost:3001/