DELETE http://localhost:3001/api/contacts/2
###
GET http://localhost:3001/api/contacts/
###
POST http://localhost:3001/api/contacts
content-type: application/json

{
    "name": "Adi Lovelace", 
    "number": "39-44-5323523"
}
###
GET http://localhost:3001/